name = "lean_examples"
version = "0.1.0"
defaultTargets = ["lean_examples"]

[[lean_lib]]
name = "Logic"

[[lean_exe]]
name = "lean_examples"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
