import Mathlib.Data.Set.Basic
import Logic.REPEAT.Syntax
import Logic.DL.Semantics
import Logic.Common.DynamicIndex

/- # Repeat Semantics

In this file the semantics of the REPEAT_arr language are defined very closely mirroring the paper.

In particular
  • Control flow traces
  • Liberal Executions
  • Variable valuation
  • Executions
  • Kripke Models associated with executions
are defined.
-/


namespace Logic.DL


/- # Control Flow Traces and their states -/


/--
Encapsulates a control flow trace, which is a triple P = (Q, prompt, tar) where
* `Q` is a sequence of States, represented as `List DynIndex`
* `prompt` is the initially executed procedure
* `tar` is the call function mapping from states to called procedures
-/
structure CFTrace where
  Q : List DynIndex
  prompt : Stmt
  tar : DynIndex → Option Proc


/--
Partial stmt function, which evaluates to the statement at a given dynamic index
-/
def stmt (cft: CFTrace) (idx: DynIndex) : Option Stmt :=
  match idx with
    | .root => some cft.prompt -- stmt(ε) = prompt, where [] represents ε
    | .cons s sym  => -- stmt(s i)
        match sym with
          | .line i =>
              match cft.tar s with   --cft.tar s is the current procedure
                | none => none       --shouldn't occur in valid cft (i.e. s i ∈ Q → ∃ p, tar s = some p)
                | some proc =>
                    match proc.body.find? (λ ls => ls.line == i) with
                      | none => none
                      | some ls => some ls.stmt

          | _ => none


/-- successor property of two states s s' -/
def nextState (cft: CFTrace) (s s': DynIndex) : Prop :=
  ∃ k,
    cft.Q[k]? = some s ∧
    cft.Q[k+1]? = some s'

/- Closure properties for the list of states Q in a cft-/

--Q[0] = ε and prompt is a call
def rootClosure (cft: CFTrace) : Prop :=
  ∃ expr args, cft.prompt = Stmt.call expr args ∧
  cft.Q[0]? = some ε

-- if s ∈ Q and stmt (s) is a call `call expr args`, then s 0 ∈ Q and tar(s) maps to a arity matching procedure
def callClosure (cft: CFTrace) : Prop :=
  ∀ s expr args,
    ((s ∈ cft.Q ∧ stmt cft s = some (Stmt.call expr args)) →

      ((s ∘ᵢ ι 0 ∈ cft.Q ∧
      ∃ proc, (cft.tar s = some proc ∧ args.length = proc.params.length)) ∧
      nextState cft s (s ∘ᵢ ι 0)))

-- if s i ∈ Q and stmt(s i) is an assignment `v[e₀] = e₁`, then s (i+1) ∈ Q
def assignClosure (cft: CFTrace) : Prop :=
  ∀ s i v e₀ e₁,
    (s ∘ᵢ ι i ∈ cft.Q ∧
     stmt cft (s ∘ᵢ ι i) = some (Stmt.assign v e₀ e₁) →

      ((s ∘ᵢ ι (i + 1) ∈ cft.Q) ∧
      nextState cft (s ∘ᵢ ι i) (s ∘ᵢ ι (i + 1))))

-- if s i ∈ Q and stmt(s i) is a returnIf `if e return ` then either s (i+1) ∈ Q or s # ∈ Q
def returnClosure (cft: CFTrace) : Prop :=
  ∀ s i e,
    (s ∘ᵢ ι i) ∈ cft.Q ∧
     stmt cft (s ∘ᵢ i) = some (Stmt.returnIf e) →

     ((s ∘ᵢ ι (i + 1) ∈ cft.Q ∧
      nextState cft (s ∘ᵢ ι i) (s ∘ᵢ ι (i + 1))
     )
      ∨
     (s ∘ᵢ # ∈ cft.Q ∧
      nextState cft (s ∘ᵢ ι i) (s ∘ᵢ #)))

-- if s i ∈ Q and stmt(s i) is `repeat`, then s $ ∈ Q, s $ 0 ∈ Q and tar(s $) = tar(s)
def repeatClosure (cft: CFTrace) : Prop :=
  ∀ s i proc,
    (s ∘ᵢ ι i ∈ cft.Q ∧
     stmt cft (s ∘ᵢ ι i) = some (Stmt.repeat) ∧
     cft.tar s = some proc) →

      (s ∘ᵢ $ ∈ cft.Q ∧
       (s ∘ᵢ $) ∘ᵢ ι 0 ∈ cft.Q ∧
       nextState cft (s ∘ᵢ ι i) (s ∘ᵢ $) ∧
       nextState cft (s ∘ᵢ $) ((s ∘ᵢ $) ∘ᵢ ι 0) ∧
       cft.tar (s ∘ᵢ $) = some proc)

-- if s $ # ∈ Q, then s # ∈ Q
def repeatReturnClosure (cft: CFTrace) : Prop :=
  ∀ s,
    (s ∘ᵢ $) ∘ᵢ # ∈ cft.Q →

      (s ∘ᵢ # ∈ cft.Q ∧
      nextState cft ((s ∘ᵢ $) ∘ᵢ #) (s ∘ᵢ #))

-- if s i # ∈ Q, then s (i + 1) ∈ Q
def callReturnClosure (cft: CFTrace) : Prop :=
  ∀ s i,
    (s ∘ᵢ ι i) ∘ᵢ # ∈ cft.Q →

      (s ∘ᵢ ι (i + 1) ∈ cft.Q ∧
      nextState cft ((s ∘ᵢ ι i) ∘ᵢ #) (s ∘ᵢ ι (i + 1)))


/- No junk properties for the list of states Q in a cft
These properties specify that only states generated by the clauses above are in the states, i.e. there are no junk states.-/

-- if s 0 ∈ Q, then s = ε or stmt(s) is a call `call expr args` with matching tar arity or s = t $ with stmt(t i) = `repeat`
def noJunkCalls (cft: CFTrace) : Prop :=
  ∀ s,
    s ∘ᵢ ι 0 ∈ cft.Q →
      (s = ε ∨
       (∃ expr args proc, s ∈ cft.Q ∧ stmt cft s = some (Stmt.call expr args) ∧
        cft.tar s = some proc ∧ args.length = proc.params.length) ∨
       (∃ t i, s = t ∘ᵢ $ ∧ t ∘ᵢ i ∈ cft.Q ∧ stmt cft (t ∘ᵢ i) = some (Stmt.repeat))
       )

-- if s i+1 ∈ Q, then s i ∈ Q and stmt(s i) is an assign `v[e₀] = e₁` or returnIf `if e return`
def noJunkLines (cft: CFTrace) : Prop :=
  ∀ s i,
    s ∘ᵢ ι (i+1) ∈ cft.Q →
      ((∃ v e₀ e₁,
       s ∘ᵢ ι i ∈ cft.Q ∧
       stmt cft (s ∘ᵢ ι i) = some (Stmt.assign v e₀ e₁)) ∨
      (∃ e,
       s ∘ᵢ ι i ∈ cft.Q ∧
       stmt cft (s ∘ᵢ ι i) = some (Stmt.returnIf e)))

-- if s # ∈ Q, then s i ∈ Q and stmt(s i) is a returnIf `if e return` or (s $)# ∈ Q
def noJunkReturns (cft: CFTrace) : Prop :=
  ∀ s,
    (s ∘ᵢ #) ∈ cft.Q →
      ((∃ i e,
       s ∘ᵢ i ∈ cft.Q ∧
       stmt cft (s ∘ᵢ i) = some (Stmt.returnIf e)) ∨
      (s ∘ᵢ $) ∘ᵢ # ∈ cft.Q)

-- if s $ ∈ Q, then s i ∈ Q and stmt(s i) is a `repeat`
def noJunkRepeats (cft: CFTrace) : Prop :=
  ∀ s,
    s ∘ᵢ $ ∈ cft.Q →
      (∃ i,
       s ∘ᵢ i ∈ cft.Q ∧
       stmt cft (s ∘ᵢ i) = some (Stmt.repeat))

/- A control flow trace is valid if
    • all states generated by the clauses a)-g) are contained in the list of states (`cftClosure`)
    • no other states are contained in the list of states (`cftNoJunk`)
    • the list of states contains no duplicate states -/

def cftClosure (cft: CFTrace) : Prop :=
  rootClosure cft ∧
  callClosure cft ∧
  assignClosure cft ∧
  returnClosure cft ∧
  repeatClosure cft ∧
  repeatReturnClosure cft ∧
  callReturnClosure cft

def cftNoJunk (cft: CFTrace) : Prop :=
  noJunkCalls cft ∧
  noJunkLines cft ∧
  noJunkReturns cft ∧
  noJunkRepeats cft

def validCFTrace (cft: CFTrace) : Prop :=
  cftClosure cft ∧ cftNoJunk cft ∧ cft.Q.Nodup

/- A few helpful projection lemmas. Instead of using a projection validCFTrace.1.2.2.2.1 or similar, you can use the
  readable named projection lemmas instead
-/

theorem validCFTrace.rootClosure (h: validCFTrace cft) :
  rootClosure cft := h.1.1

theorem validCFTrace.callClosure (h: validCFTrace cft) :
  callClosure cft := h.1.2.1

theorem validCFTrace.assignClosure (h: validCFTrace cft) :
  assignClosure cft := h.1.2.2.1

theorem validCFTrace.returnClosure (h: validCFTrace cft) :
  returnClosure cft := h.1.2.2.2.1

theorem validCFTrace.repeatClosure (h: validCFTrace cft) :
  repeatClosure cft := h.1.2.2.2.2.1

theorem validCFTrace.repeatReturnClosure (h: validCFTrace cft) :
  repeatReturnClosure cft := h.1.2.2.2.2.2.1

theorem validCFTrace.callReturnClosure (h: validCFTrace cft) :
  callReturnClosure cft := h.1.2.2.2.2.2.2

theorem validCFTrace.noJunkCalls (h: validCFTrace cft) :
  noJunkCalls cft := h.2.1.1

theorem validCFTrace.noJunkLines (h: validCFTrace cft) :
  noJunkLines cft := h.2.1.2.1

theorem validCFTrace.noJunkReturns (h: validCFTrace cft) :
  noJunkReturns cft := h.2.1.2.2.1

theorem validCFTrace.noJunkRepeats (h: validCFTrace cft) :
  noJunkRepeats cft := h.2.1.2.2.2

theorem validCFTrace.Nodup (h: validCFTrace cft) :
  cft.Q.Nodup := h.2.2

-- s i+1 ∈ Q → s i ∈ Q in a valid cft
theorem validCFTrace.line_predecessor
  (cft: CFTrace)
  (hcftValid: validCFTrace cft)
  (hline: (s ∘ᵢ ι (i+1)) ∈ cft.Q) :
  ((s ∘ᵢ i) ∈ cft.Q) := by
    rcases hcftValid.noJunkLines s i hline with ⟨v, e₀, e₁, hline', heq⟩ | ⟨e, hline', heq⟩
    · exact hline'
    · exact hline'

-- s i+1 ∈ Q → stmt (s i) is assignment or returnIf
theorem line_successor_origin
  (cft: CFTrace)
  (hcftValid: validCFTrace cft)
  (hline: (s ∘ᵢ ι (i+1) ) ∈ cft.Q):
  (∃ v e₀ e₁, stmt cft (s ∘ᵢ i) = some (Stmt.assign v e₀ e₁)) ∨
  (∃ e, stmt cft (s ∘ᵢ i) = some (Stmt.returnIf e)) := by
    rcases hcftValid.noJunkLines s i hline with ⟨v, e₀, e₁, hline', heq⟩ | ⟨e, hline', heq⟩
    · left
      exists v, e₀, e₁
    · right
      exists e

/- # Liberal Executions and variable valuations -/


/--
Liberal Execution triple Q = (P, val₀, seed), where P is a control flow trace, val₀ provides initial variable values and seed random variable values
-/
structure LiberalExecution where
  cft : CFTrace
  val₀ : Var → Int → Int
  seed : DynIndex → LocVar → Int → Int

-- val is an arbitrary variable valuation. Validity of a valuation based on a liberal execution is defined as prop mirroring the paper definition
abbrev Valuation :=
  DynIndex → Var → Int → Int

-- eval on Conds and Exprs
mutual
  def evalExpr (cft: CFTrace) (val: Valuation) (s: DynIndex): Expr → Int
    | Expr.const c => c
    | Expr.access x e => val s x (evalExpr cft val s e)
    | Expr.sub e₁ e₂ => evalExpr cft val s e₁ - evalExpr cft val s e₂
    | Expr.cond c => evalCond cft val s c

  def evalCond (cft: CFTrace) (val: Valuation) (s: DynIndex): Cond → Int
    | Cond.le e₁ e₂ => if evalExpr cft val s e₁ ≤ evalExpr cft val s e₂ then
        1
      else
        0
end

@[simp] theorem evalExpr_const :
  evalExpr cft val s (Expr.const c) = c := rfl

@[simp] theorem evalExpr_access :
  evalExpr cft val s (Expr.access x e) = val s x (evalExpr cft val s e) := rfl

@[simp] theorem evalExpr_sub :
  evalExpr cft val s (Expr.sub e₁ e₂) = evalExpr cft val s e₁ - evalExpr cft val s e₂ := rfl

@[simp] theorem evalExpr_cond :
  evalExpr cft val s (Expr.cond c) = evalCond cft val s c := rfl

@[simp] theorem evalCond_le :
  evalCond cft val s (Cond.le e₁ e₂) = if evalExpr cft val s e₁ ≤ evalExpr cft val s e₂ then 1 else 0 := rfl

-- using the simp lemmas above, simp can evaluate expressions & conditions on its own
example :
  evalExpr cft val s (Expr.const 0) = 0 := by
    simp

example :
  evalCond cft val s (Cond.le (Expr.const 1) (Expr.const 0)) = 0 := by
    simp


-- constrain val to be a valid val on given liberalExecution
-- val(ε) = seed(ε)
def valRoot (val: Valuation) (q: LiberalExecution) : Prop :=
  val ε = q.val₀

-- val (s0) (x) = val (s) (x), if x ∈ GlobVar
def valCallGlobal (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s expr args proc,
    stmt q.cft s = some (Stmt.call expr args) ∧
    q.cft.tar s = some proc →
      ∀ x, (val (s ∘ᵢ ι 0)) (Var.glob x) = val s (Var.glob x)

-- val(s0) (x) = seed(s0) (x) if x not a param
def valCallNoPar (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s expr args proc,
    stmt q.cft s = some (Stmt.call expr args) ∧
    q.cft.tar s = some proc →
      ∀ x, (x ∉ proc.params → val (s ∘ᵢ ι 0) (Var.loc x) = q.seed (s ∘ᵢ ι 0) x)

-- val(s0) (x) = val(s) (y) if x is param and y is arg for x
def valCallPar (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s expr args proc,
    stmt q.cft s = some (Stmt.call expr args) ∧
    q.cft.tar s = some proc ∧
    ∀ x y, (x, y) ∈ (List.zip proc.params args) →
      (val (s ∘ᵢ ι 0) (Var.loc x) =
       val s (match y with         -- y is of type arg, which can be either ref or var
              | Arg.var v => v
              | Arg.ref v => (Var.loc v)))

-- val(s i+1) (x) (k) = eval (s i, rhs) if stmt (s i) is assignment `x[e] = rhs` with eval(s i, e) = k
def valAssignHit (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i x k e rhs,
    stmt q.cft (s ∘ᵢ ι i) = some (Stmt.assign x e rhs) ∧
    evalExpr q.cft val (s ∘ᵢ i) e = k →
      val (s ∘ᵢ ι (i+1)) x k = evalExpr q.cft val (s ∘ᵢ i) rhs

-- val(s i+1) (x) (k) = val(s i) (x) (k) if stmt (s i) is assignment `x[e] = rhs` with eval(s i, e) ≠ k
def valAssignMiss (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i x e rhs k,
    stmt q.cft (s ∘ᵢ ι i) = some (Stmt.assign x e rhs) ∧
    evalExpr q.cft val (s ∘ᵢ ι i) e ≠ k →
      val (s ∘ᵢ ι (i+1)) x k = val (s ∘ᵢ ι i) x k

-- val(s i+1) (x) = val(s i) (x) if stmt (s i) is assignment `y[e] = rhs` with y ≠ x
def valAssignOther (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i x y e rhs,
    stmt q.cft (s ∘ᵢ ι i) = some (Stmt.assign y e rhs) ∧
    y ≠ x →
      (val (s ∘ᵢ ι (i+1)) x = val (s ∘ᵢ ι i) x)

-- val(s i+1) = val (s i) if stmt (s i) is returnIf `if e return` and s i+1 ∈ Q
def valNoReturn (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i e,
    stmt q.cft (s ∘ᵢ ι i) = some (Stmt.returnIf e) ∧
    (s ∘ᵢ ι (i+1)) ∈ q.cft.Q →
      val (s ∘ᵢ ι (i+1)) = val (s ∘ᵢ ι i)

-- val(s #) = val (s i) if stmt (s i) is returnIf `if e return` and s i+1 ∉ Q
def valReturn (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i e,
    stmt q.cft (s ∘ᵢ ι i) = some (Stmt.returnIf e) ∧
    (s ∘ᵢ ι (i+1)) ∉ q.cft.Q →
      val (s ∘ᵢ #) = val (s ∘ᵢ ι i)

-- val (s $) = val (s i) if stmt (s i) is `repeat`
def valRepeat (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i,
    stmt q.cft (s ∘ᵢ i) = some (Stmt.repeat) →
      val (s ∘ᵢ $) = val (s ∘ᵢ i)

-- val (s $ 0) = val (s $)
def valRepeatEntry (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s,
    s ∘ᵢ $ ∈ q.cft.Q →
      val ((s ∘ᵢ $) ∘ᵢ ι 0) = val (s ∘ᵢ $)


-- val (s #) = val (s $ #)
def valRepeatReturn (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s,
    (s ∘ᵢ $) ∘ᵢ # ∈ q.cft.Q →
      val (s ∘ᵢ #) = val ((s ∘ᵢ $) ∘ᵢ #)

def valCallReturnGlobal (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i expr args proc,
    stmt q.cft (s ∘ᵢ ι i) = some (Stmt.call expr args) ∧
    q.cft.tar (s ∘ᵢ ι i) = some proc →
      ∀ x, val (s ∘ᵢ ι (i+1)) (Var.glob x) = val ((s ∘ᵢ ι i) ∘ᵢ #) (Var.glob x)

-- val (s i+1) (x) = val (s i) (x) if stmtm (s i) is `call expr args` and no args are passed by `ref`
def valCallReturnByValue (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i expr args proc,
    stmt q.cft (s ∘ᵢ ι i) = some (Stmt.call expr args) ∧
    q.cft.tar (s ∘ᵢ ι i) = some proc ∧
    ∀ x, Arg.ref x ∉ args →
      (val (s ∘ᵢ ι (i+1)) (Var.loc x) = val (s ∘ᵢ ι i) (Var.loc x))

-- val (s i+1) (x) = val (s i #) (y) if stmt (s i) is `call expr args` and x was passed for param x by `ref`
def valCallReturnByRef (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i expr args proc,
    stmt q.cft (s ∘ᵢ ι i) = some (Stmt.call expr args) ∧
    q.cft.tar (s ∘ᵢ ι i) = some proc ∧
    ∀ x y, (y, Arg.ref x) ∈ List.zip proc.params args →
      (val (s ∘ᵢ ι (i +1)) (Var.loc x) = val ((s ∘ᵢ ι i) ∘ᵢ #) (Var.loc y))


-- a valuation is valid if it satisfies all clauses above
def validValuation (val: Valuation) (q: LiberalExecution) : Prop :=
  valRoot val q ∧
  valCallGlobal val q ∧
  valCallNoPar val q ∧
  valCallPar val q ∧
  valAssignHit val q ∧
  valAssignMiss val q ∧
  valAssignOther val q ∧
  valNoReturn val q ∧
  valReturn val q ∧
  valRepeat val q ∧
  valRepeatEntry val q ∧
  valRepeatReturn val q ∧
  valCallReturnGlobal val q ∧
  valCallReturnByValue val q ∧
  valCallReturnByRef val q

/- Projection theorems for validValuation -/
theorem validValuation.valRoot (q: LiberalExecution) (h: validValuation val q) :
  valRoot val q := h.1

theorem validValuation.valCallGlobal (q: LiberalExecution) (h: validValuation val q) :
  valCallGlobal val q := h.2.1

theorem validValuation.valCallNoPar (q: LiberalExecution) (h: validValuation val q) :
  valCallNoPar val q := h.2.2.1

theorem validValuation.valCallPar (q: LiberalExecution) (h: validValuation val q) :
  valCallPar val q := h.2.2.2.1

theorem validValuation.valAssignHit (q: LiberalExecution) (h: validValuation val q) :
  valAssignHit val q := h.2.2.2.2.1

theorem validValuation.valAssignMiss (q: LiberalExecution) (h: validValuation val q) :
  valAssignMiss val q := h.2.2.2.2.2.1

theorem validValuation.valAssignOther (q: LiberalExecution) (h: validValuation val q) :
  valAssignOther val q := h.2.2.2.2.2.2.1

theorem validValuation.valNoReturn (q: LiberalExecution) (h: validValuation val q) :
  valNoReturn val q := h.2.2.2.2.2.2.2.1

theorem validValuation.valReturn (q: LiberalExecution) (h: validValuation val q) :
  valReturn val q := h.2.2.2.2.2.2.2.2.1

theorem validValuation.valRepeat (q: LiberalExecution) (h: validValuation val q) :
  valRepeat val q := h.2.2.2.2.2.2.2.2.2.1

theorem validValuation.valRepeatEntry (q: LiberalExecution) (h: validValuation val q) :
  valRepeatEntry val q := h.2.2.2.2.2.2.2.2.2.2.1

theorem validValuation.valRepeatReturn (q: LiberalExecution) (h: validValuation val q) :
  valRepeatReturn val q := h.2.2.2.2.2.2.2.2.2.2.2.1

theorem validValuation.valCallReturnGlobal (q: LiberalExecution) (h: validValuation val q) :
  valCallReturnGlobal val q := h.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem validValuation.valCallReturnByValue (q: LiberalExecution) (h: validValuation val q) :
  valCallReturnByValue val q := h.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem validValuation.valCallReturnByRef (q: LiberalExecution) (h: validValuation val q) :
  valCallReturnByRef val q := h.2.2.2.2.2.2.2.2.2.2.2.2.2.2

/- Each assignment changes exactly one array cell-/
theorem assign_changes_exactly_one_cell
  (qe: LiberalExecution)
  (hVal: validValuation val qe)
  (hStmt: stmt qe.cft (s ∘ᵢ ι i) = some (Stmt.assign v e₀ e₁)):

  val (s ∘ᵢ ι (i+1)) v k =
  if evalExpr qe.cft val (s ∘ᵢ i) e₀ = k then
    evalExpr qe.cft val (s ∘ᵢ i) e₁
  else
    val (s ∘ᵢ i) v k := by

      by_cases hk: evalExpr qe.cft val (s ∘ᵢ i) e₀ = k
      · have hHit := hVal.valAssignHit qe s i v k e₀ e₁ ⟨hStmt, hk⟩
        simp[hk, hHit]
      · have hMiss := hVal.valAssignMiss qe s i v e₀ e₁ k ⟨hStmt, hk⟩
        simp[hk, hMiss]

/- # Executions and their Kripke Models -/


-- constrain liberal executions to obtain executions, mirroring the paper definition of executions

-- if stmt(s i) is returnIf `if e return` then s i+1 ∈ Q ↔ eval(s i, cond)
def execReturn (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s i e,
    stmt q.cft (s ∘ᵢ ι i) = some (Stmt.returnIf e) →
      (s ∘ᵢ ι (i+1) ∈ q.cft.Q ↔
       evalExpr q.cft val (s ∘ᵢ ι i) e = 0)

-- if stmt(s) is `call expr args`, then tar(s) = eval(s, expr)
def execCallTarget (val: Valuation) (q: LiberalExecution) : Prop :=
  ∀ s expr args proc,
    stmt q.cft s = some (Stmt.call expr args) ∧
    q.cft.tar s = some proc →
      proc.id = evalExpr q.cft val s expr


-- an execution is a valid execution if it satisfies all three constraints above
def validExecution (val: Valuation) (q: LiberalExecution) : Prop :=
  execReturn val q ∧
  execCallTarget val q


/-- An Execution contains a liberal execution `liberal` and a valuation `val`.
It also carries validity proofs for the CFTrace `hCFT`, valuation `hVal` and execution `hExec`.

This slightly deviates from the paper, where the variable valuation is defined universally
and validity of the control flow trace, valuation and the execution itself are assumed on a meta level.-/
structure Execution where
  liberal : LiberalExecution
  val: Valuation

  hCFT: validCFTrace liberal.cft
  hVal: validValuation val liberal
  hExec: validExecution val liberal


/-- An execution model is a Kripke Model `K_e` based on an execution `e`
It utilizes the generic Kripke Model definition which is polymorphic in types for atomic relations, atomic formulas and States.

These types are instantiated following the approach from the paper:
  • Dynamic index symbols `DL.DynIndexSym` are atomic relations
  • Program conditions `Cond` are atomic formulas
  • Dynamic indices `DynIndex` are states

The fields val and rel define the valuation of atomic relations and atomic formulas based on execution semantics:
  • `val (cond)` in a state s is `True` if `cond` is evaluated to 1 in program state s
  • `rel a u ua` is an a-step from state u to state u ∘ᵢ a, if u is a program state and u ∘ᵢ a is program state

Complex relations and formulas are evaluated using the generic dynamic logic semantics `DL.Logic.evalRel`, `DL.Logic.eval`
-/
def executionModel (e: Execution) :
  DL.KripkeModel DL.DynIndexSym Cond DynIndex where
  val := λ cond s ↦ s ∈ e.liberal.cft.Q ∧ evalCond e.liberal.cft e.val s cond = 1
  rel := λ a u ua ↦ u ∈ e.liberal.cft.Q ∧ ua ∈ e.liberal.cft.Q ∧ match a with
                                       | .line i =>
                                          ua = u ∘ᵢ i
                                        | .dollar =>
                                          ua = u ∘ᵢ $
                                        | .hash =>
                                          ua = u ∘ᵢ #

end Logic.DL
